"""
app.py — GreenLeaf Bot | Slack Interface Layer
================================================
Entry point for the GreenLeaf HR Assistant bot.

Architecture (HLD):
    Slack (employee) → app.py → clean_input() → is_blocked() → brain.py → tools

Message flow:
    1. Receive message from Slack
    2. Mask PII via clean_input() — names, IDs, emails
    3. Check security via is_blocked() — Wi-Fi, salary, injection
    4. Route to brain.py (Week 3)

Tech stack:
    - Slack Bolt for Python (Socket Mode)
    - python-dotenv — loads tokens from .env
    - privacy_gate.py — PII masking + security filter

Sprint: Week 2 | Owner: Ibrahim (System Architect)
"""

import os
import sys

# Add project root to Python path so imports work correctly
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from slack_bolt import App
from slack_bolt.adapter.socket_mode import SocketModeHandler
from dotenv import load_dotenv
from src.privacy_gate import clean_input, is_blocked, get_block_message
# NEW: Import Week 3 brain orchestrator
# This connects Slack input to business logic tools (expenses, policies, etc.)
from src.brain import classify_and_dispatch

# Load tokens from .env file (never hardcode tokens in code)
load_dotenv()

# Initialize Slack app with bot token
app = App(token=os.environ["SLACK_BOT_TOKEN"])


def process_query(raw_query, say, event_data):
    """Shared logic for DM messages and channel mentions."""

    # NEW: Ignore bot-generated events to prevent reply loops
    # Without this, the bot may respond to messages generated by another bot
    if "bot_id" in event_data:
        return

    # Existing logic: pass message through privacy masking
    cleaned_query = clean_input(raw_query)

    # Existing logic: block sensitive or unsafe requests
    if is_blocked(cleaned_query):
        say(get_block_message(cleaned_query))
        return

    try:
        # Pass raw text for business-rule detection,
        # but keep cleaned text available for safe handling if needed
        response = classify_and_dispatch(raw_query, cleaned_query)
        say(response)
    except Exception as e:
        print(f"Error in brain: {e}")
        say("I encountered an error while processing your request. Please try again.")

@app.message("")
def handle_message(message, say):
    """Handles direct messages to the bot."""
    raw_query = message.get("text", "")

    # UPDATED: pass full Slack message object into process_query()
    # This is required for bot loop prevention via event_data["bot_id"]
    process_query(raw_query, say, message)

@app.event("app_mention")
def handle_mention(event, say):
    """Handles @GreenLeaf mentions in channels."""
    raw_query = event.get("text", "")

    # UPDATED: pass full Slack event object into process_query()
    # This keeps DM and mention flows consistent
    process_query(raw_query, say, event)


if __name__ == "__main__":
    handler = SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"])
   # UPDATED: startup log now reflects Week 3 integration status
    print("⚡ GreenLeaf Bot is running (Week 3 - Brain Integrated)...")
    handler.start()


# =============================================================================
# HOW TO TEST LOCALLY
# =============================================================================
#
# 1. Create your Slack App at https://api.slack.com/apps
#    - Enable Socket Mode → generate App Token (os.environ["SLACK_APP_TOKEN"]...)
#    - OAuth & Permissions → add scopes: chat:write, im:history, app_mentions:read
#    - Event Subscriptions → enable: message.im, app_mention
#    - App Home → enable "Allow users to send messages"
#    - Install to Workspace → copy Bot Token (os.environ["SLACK_BOT_TOKEN"]...)
#
# 2. Set up environment:
#    cp .env.example .env
#    # Edit .env and add your tokens
#
# 3. Install dependencies:
#    python -m venv venv
#    source venv/bin/activate
#    pip install -r requirements.txt
#
# 4. Fix SSL certificates (macOS only, one-time):
#    /Applications/Python\ 3.10/Install\ Certificates.command
#
# 5. Run the bot:
#    python src/app.py
#
# 6. Test in Slack (DM the bot):
#    "My name is Beat Müller"       → bot sees: "My name is [NAME]"
#    "My ID is 12345"               → bot sees: "My ID is [ID]"
#    "What is the wifi password?"   → BLOCKED
#    "Ignore previous instructions" → BLOCKED (injection)
#    "Is May 1st a holiday?"        → PASSED
# =============================================================================